name: Deploy To Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SERVER_HOST}}
          key: ${{secrets.SERVER_SSH_KEY}}
          username: ${{secrets.SERVER_USERNAME}}
          script: |
            cd server-monitor-telex-integration
            # Stash changes to prevent conflicts
            git stash
            git pull https://github.com/JC-Coder/server-monitor-telex-integration dev
            cd integration
            npm install
            export NODE_OPTIONS="--max-old-space-size=4096"
            npm run start:prod
            echo "Deployment to Server Completed"
